# Data-X Spring 2019: Homework 06 

## Name : Zihui Xu
## SID : 3034305174
## Course (IEOR 135/290) : 290

### Machine Learning



In this homework, you will do some exercises with prediction. We will cover these algorithms in class, but this is for you to have some hands on with these in scikit-learn. You can refer - https://github.com/ikhlaqsidhu/data-x/blob/master/05a-tools-predicition-titanic/titanic.ipynb

Display all your outputs.


In [1]:
import numpy as np
import pandas as pd

In [2]:
 # machine learning libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier



__ 1. Read __`diabetesdata.csv`__ file into a pandas dataframe. 
About the data: __

1. __TimesPregnant__: Number of times pregnant 
2. __glucoseLevel__: Plasma glucose concentration a 2 hours in an oral glucose tolerance test 
3. __BP__: Diastolic blood pressure (mm Hg)  
5. __insulin__: 2-Hour serum insulin (mu U/ml) 
6. __BMI__: Body mass index (weight in kg/(height in m)^2) 
7. __pedigree__: Diabetes pedigree function 
8. __Age__: Age (years) 
9. __IsDiabetic__: 0 if not diabetic or 1 if diabetic) 








In [3]:
#Read data & print the head
df=pd.read_csv('diabetesdata.csv')
df.head()

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  IsDiabetic
0              6         148.0  72        0  33.6     0.627  50.0           1
1              1           NaN  66        0  26.6     0.351  31.0           0
2              8         183.0  64        0  23.3     0.672   NaN           1
3              1           NaN  66       94  28.1     0.167  21.0           0
4              0         137.0  40      168  43.1     2.288  33.0           1

**2. Calculate the percentage of Null values in each column and display it. **

In [4]:
columns = df.columns
percent_missing = df.isnull().sum() * 100 / len(df)
miss_precent=pd.DataFrame({'percent_missing': percent_missing})
miss_precent

percent_missing
TimesPregnant         0.000000
glucoseLevel          4.427083
BP                    0.000000
insulin               0.000000
BMI                   0.000000
Pedigree              0.000000
Age                   4.296875
IsDiabetic            0.000000

**3. Split __`data`__  into  __`train_df`__ and __`test_df`__  with 15% as test.**


In [5]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df, test_size=0.15)
train_df.head()

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
289              5         108.0  72       75  36.1     0.263  33.0   
377              1          87.0  60       75  37.2     0.509  22.0   
594              6         123.0  72      230  33.6     0.733  34.0   
653              2         120.0  54        0  26.8     0.455   NaN   
754              8         154.0  78        0  32.4     0.443  45.0   

     IsDiabetic  
289           0  
377           0  
594           0  
653           0  
754           1

**4. Display the means of the features in train and test sets. Replace the null values in  __`train_df`__ and __`test_df`__  with the mean of EACH feature column separately for train and test. Display head of the dataframes.**

In [6]:
mean_train=train_df.mean()
print('Means of the features in train sets:\n',mean_train)
mean_test=test_df.mean()
print('Means of the features in test sets:\n',mean_test)

# Fill NaN Values in the datasets
   
for dataset in train_df.columns:
    train_df.loc[:,dataset]=train_df.loc[:,dataset].fillna(np.mean(train_df.loc[:,dataset]))
for dataset in test_df.columns:
    test_df.loc[:,dataset]=test_df.loc[:,dataset].fillna(np.mean(test_df.loc[:,dataset]))

display(train_df.head())
display(test_df.head())



Means of the features in train sets:
 TimesPregnant      3.892638
glucoseLevel     121.871383
BP                69.641104
insulin           82.932515
BMI               32.267025
Pedigree           0.480551
Age               33.574639
IsDiabetic         0.354294
dtype: float64
Means of the features in test sets:
 TimesPregnant      3.577586
glucoseLevel     116.267857
BP                66.094828
insulin           62.189655
BMI               30.450000
Pedigree           0.423121
Age               32.125000
IsDiabetic         0.318966
dtype: float64


/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree        Age  \
289              5         108.0  72       75  36.1     0.263  33.000000   
377              1          87.0  60       75  37.2     0.509  22.000000   
594              6         123.0  72      230  33.6     0.733  34.000000   
653              2         120.0  54        0  26.8     0.455  33.574639   
754              8         154.0  78        0  32.4     0.443  45.000000   

     IsDiabetic  
289           0  
377           0  
594           0  
653           0  
754           1

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
158              2          88.0  74       53  29.0     0.229  22.0   
157              1         109.0  56      135  25.2     0.833  23.0   
4                0         137.0  40      168  43.1     2.288  33.0   
368              3          81.0  86       66  27.5     0.306  22.0   
535              4         132.0   0        0  32.9     0.302  23.0   

     IsDiabetic  
158           0  
157           0  
4             1  
368           0  
535           1

**5. Split __`train_df`__ & __`test_df`__   into  __`X_train`__, __`Y_train`__  and __`X_test`__, __`Y_test`__. __`Y_train`__  and __`Y_test`__ should only have the column we are trying to predict,  __`IsDiabetic`__.**

In [7]:
X_tra=train_df.iloc[:,:-1]
Y_tra=train_df['IsDiabetic']

X_test=test_df.iloc[:,:-1]
Y_test=test_df['IsDiabetic']


**6. Use this dataset to train perceptron, logistic regression and random forest models using 15% test split. Report training and test accuracies. Try different hyperparameter values for these models and see if you can improve your accuracies.**

In [8]:
# 6a. Logistic Regression
logreg = LogisticRegression(solver='lbfgs',max_iter=1000)                                # instantiate
logreg.fit(X_tra, Y_tra)                                 # fit
Y_pred = logreg.predict(X_test)                               # predict
acc_logreg = sum(Y_pred ==Y_test)/len(Y_test)*100                # evaluate

print('Logistic Regression labeling accuracy:', str(round(acc_logreg,2)),'%')


Logistic Regression labeling accuracy: 80.17 %


In [9]:
# 6b. Perceptron
perceptron = Perceptron(tol=1^-5,early_stopping=False,n_iter_no_change=5)                                    # instantiate 
perceptron.fit(X_tra, Y_tra)                             # fit
acc_perceptron = perceptron.score(X_test, Y_test)              # predict + evalaute

print('Perceptron labeling accuracy:', str(round(acc_perceptron*100,2)),'%')


Perceptron labeling accuracy: 70.69 %


In [10]:
# 6c. Random Forest

random_forest = RandomForestClassifier(n_estimators=500)   # instantiate
random_forest.fit(X_tra, Y_tra)                         # fit
acc_rf = random_forest.score(X_test, Y_test)                  # predict + evaluate

print('K-Nearest Neighbors labeling accuracy:', str(round(acc_rf*100,2)),'%')

K-Nearest Neighbors labeling accuracy: 80.17 %


**7. For your logistic regression model - **

**a . Compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your train set and display it. Also display the predicted class for those samples from your logistic regression model trained before. **


In [11]:
# Pick the top 10 samples
X_tra_10=X_tra.head(10)
# Compute the log probability of class in IsDiabetic
Log=logreg.predict_log_proba(X_tra_10)
print ('Log probabilities: \n',' Class 0        Class 1 \n',Log)

# Display the predicted class from logistic regression model
y_pred=logreg.predict(X_tra_10)
print('Actual classes: \n',y_pred)


Log probabilities: 
  Class 0        Class 1 
 [[-0.29326434 -1.36973212]
 [-0.1201498  -2.17848947]
 [-0.52212649 -0.89957534]
 [-0.23548253 -1.56155038]
 [-1.29426564 -0.32034174]
 [-0.51150089 -0.91527869]
 [-0.36740928 -1.17936523]
 [-0.20405025 -1.68967984]
 [-0.50210108 -0.92952194]
 [-0.12523513 -2.13952642]]
Actual classes: 
 [0 0 0 0 1 0 0 0 0 0]


**b . Now compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your test set and display it. Also display the predicted class for those samples from your logistic regression model trained before.
 (using the model trained on the training set)**


In [12]:
# Pick the top 10 samples from test set
X_test_10=X_test.head(10)
# Compute the log probability of class in IsDiabetic
Log_test=logreg.predict_log_proba(X_test_10)
print ('Log probabilities: \n',' Class 0        Class 1 \n',Log_test)
# Display the predicted class from logistic regression model
y_pred_test=logreg.predict(X_test_10)
print('Actual classes: \n',y_pred_test)



Log probabilities: 
  Class 0        Class 1 
 [[-0.05637346 -2.9038112 ]
 [-0.13383547 -2.0773156 ]
 [-1.92309272 -0.15800472]
 [-0.0432535  -3.16222582]
 [-0.64289184 -0.74606238]
 [-0.9599657  -0.48273395]
 [-0.10254886 -2.32825222]
 [-0.58508757 -0.81431436]
 [-0.17668048 -1.82045227]
 [-1.10681212 -0.40139027]]
Actual classes: 
 [0 0 1 0 0 1 0 0 0 1]


**c . What can you interpret from the log probabilities and the predicted classes?**



The class with the higher value of log probabilities is the same as the actual predicted class from the logistic regression model. The principle is true for both training and testing dataset.

**8. Is mean imputation is the best type of imputation (as we did in 4.) to use? Why or why not? What are some other ways to impute the data?**

The answer is unsure, because it depends on the situation of the application. For our case, it is ok to use the mean imputation for missing values from age column.But from the Titanic example, when the data is missing on embarked values, is impossible to take the mean value. So, for that case, we used mode imputation. There are many other ways to impute the data: median, mode imputation.

## Extra Credit (2 pts) - MANDATORY for students enrolled in IEOR 290


**9.  Implement the K-Nearest Neighbours (https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm) algorithm for k=1 from scratch in python (do not use KNN from existing libraries). KNN uses Euclidean distance to find nearest neighbors. Split your dataset into test and train as before. Also fill in the null values with mean of features as done earlier. Use this algorithm to predict values for 'IsDiabetic' for your test set. Display your accuracy. **

In [13]:
import math

def classifyAPoint(points,p,k): 
    ''' 
     This function finds classification of p using 
     k nearest neighbour algorithm. 
      Parameters -  
          points : Dictionary of training points having two keys - 0 and 1 
                   Each key have a list of training data points belong to that  
  
          p : A touple ,test data point 
  
          k : number of nearest neighbour to consider
    '''
  
    distance=[] 
    for group in points: 
        for feature in points[group]: 
            total=0
            for i in range(len(feature)):
                diff=feature[i]-p[i]
                total=total+diff**2
            #calculate the euclidean distance of p from training points  
            euclidean_distance = math.sqrt(total) 
  
            # Add a touple of form (distance,group) in the distance list 
            distance.append((euclidean_distance,group)) 
  
    # sort the distance list in ascending order 
    # and select first k distances 
    distance = sorted(distance)[:k] 
  
    freq1 = 0 #frequency of group 0 
    freq2 = 0 #frequency og group 1 
  
    for d in distance: 
        if d[1] == '0': 
            freq1 += 1
        elif d[1] == '1': 
            freq2 += 1
    return 0 if freq1>freq2 else 1
  


In [14]:
y0=[]
y1=[]
for index, row in Y_tra.iteritems():
    if row==0:
        y0.append(index)
    else:
        y1.append(index)
        
x0=X_tra.loc[y0,:].values.tolist()
x1=X_tra.loc[y1,:].values.tolist()

dic={'0':x0,'1':x1}


In [15]:
result=[]
for i in range(len(X_test)):
    result.append(classifyAPoint(dic,X_test.iloc[i,:],1))
print(result)

[0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]


In [16]:
correct = 0
for i in result:
    if Y_test.iloc[i] == result[i]:
        correct += 1
accuracy = float(correct)/len(result) *100  #accuracy 

print(accuracy)

80.17241379310344
